### ISSUE TITLE
Error that spams console and breaks /dh reload

### ISSUE THREAD

**Issue by SladeHazard** [DecentSoftware-eu/DecentHolograms#102]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

N/A

### Solution

Console keeps getting spammed by an error and if I do /dh reload all the holograms disappear and don't come back because of this error I believe, it didn't use to happen before, I think it might be because im using holographicdisplays and decentholograms at the same time, can't be bothered changing the api of 22 plugins.

https://hastebin.com/wakonizeme.yaml

### Server Version

1.12.2 Paper

### Client Version

N/A

### Plugin Version

2.7.9

### Log

https://hastebin.com/wakonizeme.yaml

**Comment by Andre601** [comment]
Please share your full server log. This error alone won't help us finding the issue you're encountering

**Comment by SladeHazard** [comment]
> Please share your full server log. This error alone won't help us finding the issue you're encountering

https://hastebin.com/cedarogiwo.makefile

**Comment by d0by1** [comment]
Hello, this should now be fixed in v2.7.10, thanks for your help!
