### ISSUE TITLE
SERVER CRASH!

### ISSUE THREAD

**Issue by Regomy** [DecentSoftware-eu/DecentHolograms#103]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms... YES
2. Do something... USING
3. Do something else... https://timings.aikar.co/dev/?id=e7108dc03c6e40f1bea60fe4e6b4ff93
4. This happens... https://timings.aikar.co/dev/?id=e7108dc03c6e40f1bea60fe4e6b4ff93

### Solution

https://timings.aikar.co/dev/?id=e7108dc03c6e40f1bea60fe4e6b4ff93

### Server Version

FLAMEPAPER 1,8,8

### Client Version

1.8

### Plugin Version

This server is running DecentHolograms v2.7.9 by d0by : https://www.spigotmc.org/resources/96927/

### Log

NO EMPTY LOG

**Comment by Andre601** [comment]
And where is the proof of a server crash?

**Comment by Regomy** [comment]
> And where is the proof of a server crash?

No, the server just shut down, in the log line breaks off, at the message about the economy, that the player accrued 10 coins, the log ends there. Server status is off. I am using flamepaper, on the spigot did not look, can not figure out the timings, but put just paperspigot, see in spark as your plugin for a couple of minutes loads: https://spark.lucko.me/KuWwHnDd97
