### ISSUE TITLE
Converting from CMI seems to not save after restarting server.

### ISSUE THREAD

**Issue by andrew121410** [DecentSoftware-eu/DecentHolograms#104]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

Convert hologram/s from CMI then restart your Minecraft Server after restarting there will be no holograms

### Server Version

git-Purpur-1889 (MC: 1.19.3)*

### Client Version

1.19.3

### Plugin Version

v2.7.9

### Log

na

**Comment by Andre601** [comment]
Any logs? Exceptions? Errors?

**Comment by d0by1** [comment]
We can't help you without logs.
