### ISSUE TITLE
Armorstand visibility flickering

### ISSUE THREAD

**Issue by EagL3-GIT** [DecentSoftware-eu/DecentHolograms#107]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms...
2. Enable built-in damage indicators / regen indicators
3. (I am using MythicLib indicators but result is the same)
4. U can see armorstand flickering when damaging

Video: https://cdn.discordapp.com/attachments/606787319583866900/1064192067800158318/stand.mp4

### Server Version

git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)

### Client Version

1.19.2

### Plugin Version

DecentHolograms version 2.7.9

### Log

No errors.

**Comment by d0by1** [comment]
This has been fixed in 2.7.10. Thanks for reporting this issue!
