### ISSUE TITLE
Hide the holograms, behind the blocks from the player's field of view.

### ISSUE THREAD

**Issue by Regomy** [DecentSoftware-eu/DecentHolograms#108]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

I have a lot of holograms on my spawn, and there are 2 floors, these holograms severely spoil the view, they can be seen through the blocks, and they are bright.

### Feature

Check for blocks, if the hologram is behind the blocks, hide it until it is in the player's direct line of sight.

### Alternatives

No.

**Comment by Andre601** [comment]
Something like that is to my knowledge planned for DH v3

**Comment by d0by1** [comment]
This is planned for later updates, not any time soon though. I will close this issue for now.
