### ISSUE TITLE
When pressed, hide the hologram for n seconds.

### ISSUE THREAD

**Issue by Regomy** [DecentSoftware-eu/DecentHolograms#109]
When pressed, hide the hologram for n seconds.

**Comment by d0by1** [comment]
Issue teplates exist. Also, explain a little better, I don't even understand what you want.

**Comment by Regomy** [comment]
@d0by1 ?? reply me

**Comment by d0by1** [comment]
I closed the issues because I wanted you to use the feature request teplate. Nevermind, I can implement this feature but I will be easily avoidable by reconnecting. Like if the placeholder gets hidden and the player reconnects, it will be shown again.
