### ISSUE TITLE
Hitbox is not correct

### ISSUE THREAD

**Issue by ytnoos** [DecentSoftware-eu/DecentHolograms#110]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms
2. Have a client that can see armorstand even if invisible
3. Create an hologram and check the hitboxes

I don't know why but armorstands are not spawned correctly. The first line must be higher than every armorstand since it reperesent the name of the first armorstand. Also as you can see in the screenshots a single hologram has an huge upper hitbox, meanwhile it should be definitely under the line and small.

Correct behavior (using custom hologram plugins): https://imgur.com/a/BACaA0x
Decent Holograms wrong behavior: https://imgur.com/a/qPfWlN2

### Server Version

1.8.8

### Client Version

1.8.8

### Plugin Version

2.7.9

### Log

no log

**Comment by d0by1** [comment]
Hello, I made some adjustments in 2.7.10, it's probably never gonna be perfect because DH's click detection is a little strange. It should be better thought, let me know.

**Comment by ytnoos** [comment]
I tested, first of all thanks for the fast response.
The situation improved a bit but it can be improved even more. 
Actually it looks like this: https://imgur.com/a/TbsFAt8
I tried to set all armorstand non-small and this is the correct behavior: https://imgur.com/a/0LmrDEQ

**Comment by MisterLolxd2** [comment]
This problem is especially acute when the damage indicator is activated, because then this option causes empty hits.

**Comment by ytnoos** [comment]
The problem with hitbox is that when you have a paginated hologram and you switch pages, the ArmorStand will respawn and have a different Entity ID every time. The client will break the hitbox order in this way. I fixed every hitbox issue by having all armorstand non small and never respawning the armorstand itself. So I had to make my own pagination system which only sets the name to existing HologramLine instead of respawning them. Here you can see how much precise it is. (this was impossible to do with the provided API)

https://imgur.com/a/TfFN57Y

**Comment by sovtec** [comment]
This^^

**Comment by d0by1** [comment]
Hey! Just a little update on this. 

I decided to just leave it as it is for now. It would be too much work to change it in the current codebase and it's simply not worth it. I'm currently working on a full rewrite of the plugin, in which I'm going to implement a much better system for click detection, page switching and the entity ids of lines. 

I appreciate the help and I will do my best to solve this problem in version 3.0 (the rewrite).

**Comment by d0by1** [comment]
I will now close this. The issue will be fixed in v3.0.
