### ISSUE TITLE
Holograms not showing up

### ISSUE THREAD

**Issue by PalmTamino** [DecentSoftware-eu/DecentHolograms#111]
**Reproducing**:
This just sometimes happens and I didn't find a way to trigger it manually.

**Everything about the bug**:
Sometimes the Holograms are just not showing up, but only on a single minecraft instance, the others see it. A reload of the plugin fixes that bug for that single instance too.

**Video**:
https://streamable.com/wvgjnb

**Versions**:
DecentHolograms: 2.7.10
Server: Current: git-Purpur-1886 (MC: 1.19.3)*
Client: 1.19.3

**Comment by d0by1** [comment]
Hello, could you please provide the following information, to help me find the issue, please?
- Have you tried this with vanilla MC? (And what client are you using?)
- Do you use any plugin, that somehow modify outgoing packets?
- When does this happen? (When you join the server, when you go far away and come back, ...)
- Does anything show up in console? (Errors, warnings, etc..)
- Could you also share at least one of the hologram's files please?

**Comment by PalmTamino** [comment]
1) Tried it and had the bug also there, but this time I used 1.19.3 with some fabric mods. 
2) Yes, multiple
3) Sometimes when joining
4) Nope, nothing in console, plugin loads without errors. Everything fine.
5) Yes of course. https://paste.gg/p/anonymous/359b95f8bc094b28966f03fda452bba0

**Comment by d0by1** [comment]
Well, I still don't see anything that could cause it. Anyhow, does this only happen on that single server or have you tried on multiple servers (with different plugins, etc..)?

**Comment by PalmTamino** [comment]
> Well, I still don't see anything that could cause it. Anyhow, does this only happen on that single server or have you tried on multiple servers (with different plugins, etc..)?

I only saw it on our lobby i think, but not 💯 % sure unfortunately:/

**Comment by d0by1** [comment]
It's kind of the last thing that comes to my mind. That it's caused by something in the server.

**Comment by PalmTamino** [comment]
> hat it's caused by something on the server.

Hmm, but we didn't have the issue with HD. I know this doesn't help much :/

Here a screenshot: 
![grafik](https://user-images.githubusercontent.com/36358673/216786956-f02e5481-4647-484c-b2c1-b067310d252e.png)
Both same version of mc same time but different account.

**Comment by d0by1** [comment]
Hello, there have been many changes around hologram visibility updates since this issue was originally discussed. Could you just confirm that the issue has been fixed?

**Comment by d0by1** [comment]
Hey, due to this issue being inactive, I will now close it. If you encounter the same problem, or any other problem, in the future, please create a new issue.
