### ISSUE TITLE
Hologram disappearing after dying

### ISSUE THREAD

**Issue by c0dingnoobi** [DecentSoftware-eu/DecentHolograms#112]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Use any version above 2.8 (since 2.8 was the latest which worked)
2. Start server using vanilla spigot 1.8 without plugins
3. Spawn a hologram using `dh create` command
5. set ur respawnpoint near to the hologram
5. Die and respawn
--> hologram needs to be reloaded using `dh reload` in order to show up again 

Has been tested on 1.19.3. Bug does not seem to be reproduceable there

### Server Version

Spigot 1.8.8

### Client Version

Vanilla 1.8.8

### Plugin Version

v2.7.11

### Log

idk what kind of log is being expected here

**Comment by d0by1** [comment]
Hello, this should now be fixed in 2.8.0. Thanks for reporting it!
