### ISSUE TITLE
Click through holograms

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [DecentSoftware-eu/DecentHolograms#113]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

I can't select or click these signs in the middle when there is a hologram here. The armor stand blocked me.
![image](https://user-images.githubusercontent.com/45261195/217039523-d3300147-081c-40ed-bb66-946c68f19ffe.png)

### Feature

A new option to make a hologram completely not selectable and be able to click through like Holographic Displays.

**Comment by Aira-Sakuranomiya** [comment]
Also, damage display and healing display is selectable too. It would be nice if you guys can make it not selectable.

**Comment by d0by1** [comment]
Hello, this has been fixed in release 2.7.12, thanks for reporting it!
