### ISSUE TITLE
Damage display and Healing display will block player to interact things.

### ISSUE THREAD

**Issue by WMGameLive** [DecentSoftware-eu/DecentHolograms#114]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

Enable damage display in config, and attack a mob, then attack again after the damage displayed.
I didn't notice this issue when I was using 2.7.9, and no players have reported this issue, so I don't know which version started to have this issue, I just updated to 2.7.11 yesterday and many players reported this issue to me.

### Server Version

1.19.3

### Client Version

1.19.3

### Plugin Version

2.7.11

### Log

no error in console.

**Comment by d0by1** [comment]
Hello, this has been fixed in release 2.7.12, thanks for reporting it!
