### ISSUE TITLE
Holograms are blocking interact of AST armorstands

### ISSUE THREAD

**Issue by EagL3-GIT** [DecentSoftware-eu/DecentHolograms#115]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Create armorstand using Armor Stand Tools plugin (AST)
2. Create hologram above this AST armorstand
3. Put a command on AST armorstand
4. If AST armorstand is behind "invisible hologram armorstands" u cant click on it
    so ur command will not be performed. (Its like blocking view) 
    
    VIDEO:  https://imgur.com/a/2ehfQDD

### Solution

Make them somehow "invisible" for player so game do not recognize it as clickable armorstand (?)
I am pretty sure it was working fine some versions ago. (Probably before 2.7.10)

### Server Version

git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)

### Client Version

1.19.2

### Plugin Version

2.7.11

### Log

No errors.

**Comment by d0by1** [comment]
Hello, this has been fixed in release 2.7.12, thanks for reporting it!
