### ISSUE TITLE
Hide the hologram, behind another hologram.

### ISSUE THREAD

**Issue by Regomy** [DecentSoftware-eu/DecentHolograms#118]
Hide the hologram, behind another hologram. It means that if a vector of a player's gaze passes through 1 hologram and touches the 2nd one, which in its turn stands behind the first one, then hide the second one. Otherwise it looks awful, and I can't rearrange them)

**Comment by Andre601** [comment]
1. Use the template and don't edit it out.
2. I can imagine this being extremely resource intense as DH would need to check constantly in what direction a player looks. Increase that by x players and you get a resource hog.

**Comment by sovtec** [comment]
Addon for DH 🤔
