### ISSUE TITLE
Updating the hologram using the api doesn't work correctly

### ISSUE THREAD

**Issue by KamlaXPL** [DecentSoftware-eu/DecentHolograms#119]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

DHAPI.setHologramLines() - it doesn't refresh the hologram, only when you walk away from it and come back will it send you the corrected lines

### Server Version

1.8.8

### Client Version

1.8.8

### Plugin Version

2.7.11

### Log

No logs

**Comment by d0by1** [comment]
Hello, I will need to see your code + Server and Plugin versions. Also, what do you mean by "doesn't refresh", is the line content wrong, or alignment of lines?

**Comment by d0by1** [comment]
I can't help you without you providing the mentioned info. I also tested the method and it works just fine. I will now close this issue.

**Comment by KamlaXPL** [comment]
The content of the line doesn't display.

Code:
```
DHAPI.setHologramLines(DHAPI.getHologram("test"), Arrays.asList("test 1", "test 2"));
Bukkit.getScheduler().runTaskLater(this, () -> DHAPI.setHologramLines(DHAPI.getHologram("test"), Arrays.asList("test 3", "test 4")), 100L);
```

if the player is standing next to the hologram, when the scheduler is executed, the content won't update but the player will still see "test 1" and "test 2", and if the player walks away from the hologram, the content will disappear and the player will come closer again, the content will be "test 3" "test 4".
