### ISSUE TITLE
Entity size option

### ISSUE THREAD

**Issue by Reeferx7** [DecentSoftware-eu/DecentHolograms#124]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

I am unable to achieve '...'
I think it would be useful for '...'

### Feature

Hello, I don't know if that is possible, is any way to add option for the entities to change the size of them? To make them a lot smaller or larger? 
Another idea is to add the entity inside spawner spinning.
We can customize a lot more the holo if that is possible.

### Alternatives

It would also be possible by doing '...'

**Comment by Andre601** [comment]
It's not possible. Mob sizes are defined by MC. The only mob that allows resizing of some sort is the Slime.
