### ISSUE TITLE
Updating the hologram using the api still doesn't work correctly

### ISSUE THREAD

**Issue by KamlaXPL** [DecentSoftware-eu/DecentHolograms#126]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

The content of the line doesn't display.

Code:
```
DHAPI.setHologramLines(DHAPI.getHologram("test"), Arrays.asList("test 1", "test 2"));
Bukkit.getScheduler().runTaskLater(this, () -> DHAPI.setHologramLines(DHAPI.getHologram("test"), Arrays.asList("test 3", "test 4")), 100L);
```

if the player is standing next to the hologram, when the scheduler is executed, the content won't update but the player will still see "test 1" and "test 2", and if the player walks away from the hologram, the content will disappear and the player will come closer again, the content will be "test 3" "test 4".

### Server Version

1.8.8

### Client Version

1.8.8

### Plugin Version

2.8.1

### Log

No logs

**Comment by d0by1** [comment]
Hello, I tested your exact code with DH 2.8.5 and it seems to work correctly. Can you confirm that the issue has been fixed?
