### ISSUE TITLE
Console get some errors when player teleport.

### ISSUE THREAD

**Issue by WMGameLive** [DecentSoftware-eu/DecentHolograms#127]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

idk.
Not everytime, but very often.

### Server Version

1.19.4

### Client Version

1.19.4

### Plugin Version

2.8.1

### Log

https://pastebin.com/j53FhFLJ

**Comment by d0by1** [comment]
Hello, this should now be fixed in version 2.8.2, thanks for reporting it!
