### ISSUE TITLE
The choice for damage displays

### ISSUE THREAD

**Issue by Darkseno** [DecentSoftware-eu/DecentHolograms#129]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

No problem

### Feature

I would just like to have the possibility to disable the damage displayed for entities and keep it for players, because I have a big server with a lot of spawners and auto farm and I start to have a lag because of countless damage holograms

### Alternatives

It would also be possible by doing '...'

**Comment by Andre601** [comment]
This is already a thing...
https://github.com/DecentSoftware-eu/DecentHolograms/blob/main/src/main/resources/config.yml#L73-L75

**Comment by d0by1** [comment]
As Andre said, this is already a feature, I will now close this issue.
