### ISSUE TITLE
Add Folia Support

### ISSUE THREAD

**Issue by Aitooor** [DecentSoftware-eu/DecentHolograms#132]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Feature

Folia url: https://github.com/PaperMC/Folia

I think it will be usefull for creation of async servers.

**Comment by Andre601** [comment]
For clarity sake: Duplicate of #123

**Comment by Aitooor** [comment]
> For clarity sake

That why i close the issue..
