### ISSUE TITLE
Nullpointer Exception

### ISSUE THREAD

**Issue by SirCraftypants** [DecentSoftware-eu/DecentHolograms#134]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

I have no idea why it happened or what triggered it if anything did, it just appeared in my console.

### Server Version

Paper 1.19.4 #530

### Client Version

1.19.4

### Plugin Version

2.8.1

### Log

 https://paste.helpch.at/hibipufovo.md

**Comment by d0by1** [comment]
Hello, this should now be fixed in version 2.8.2, thanks for reporting it!
