### ISSUE TITLE
Item displays in custom animation file

### ISSUE THREAD

**Issue by xDacon** [DecentSoftware-eu/DecentHolograms#135]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

#ICON doesn't work in animation files

### Feature

Cycling through different item displays in an animation

**Comment by Andre601** [comment]
This is intentional to my knowledge as it could be very laggy for the client to constantly change items.
