### ISSUE TITLE
Enable/Disable Holograms per Player

### ISSUE THREAD

**Issue by MisterLolxd2** [DecentSoftware-eu/DecentHolograms#137]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Feature

This is both a proposal and a question:

Would it be possible to add options such as disabling/enabling a given one hologram or/and all holograms per player?
Or something like a permission, if the player does not have a given permission, he simply does not see this hologram.
A useful option when a player whose computer does not work could turn off holograms to minimize FPS drops.
I searched the wiki and only found a "global" disabling/enabling of the hologram in question

**Comment by Andre601** [comment]
You can just add a permission to a hologram. If the player doesn't have it, it won't be shown

**Comment by MisterLolxd2** [comment]
How? I see in wiki permission only per page.

**Comment by MisterLolxd2** [comment]
Thanks.
