### ISSUE TITLE
Open link action

### ISSUE THREAD

**Issue by JamieIsGeek** [DecentSoftware-eu/DecentHolograms#139]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

I am unable to achieve when someone clicks on a hologram using an action, it trys to open a URL for the user, similar to clicking on text.
I think it would be useful for linking documents or wikis in holograms. I am trying to link a charity donation page to mine

### Feature

I would like to see an action where it can open a URL for the player that clicked the hologram

### Alternatives

It would also be possible by doing '...'

**Comment by Andre601** [comment]
This is impossible to do. `open_url` is only doable within JSON messages in chat, not for anything else.
