### ISSUE TITLE
Needs update to 1.20 paper

### ISSUE THREAD

**Issue by TurretedAsh** [DecentSoftware-eu/DecentHolograms#141]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms...
2. Do something...
3. Do something else...
4. This happens...

### Server Version

Latest paper experimental build 

### Client Version

1.20

### Plugin Version

v2.8.1

### Log

https://pastebin.com/vKpGx0eJ

**Comment by d0by1** [comment]
Hello, I just released a new version - 2.8.2 - which supports 1.20. I will now close this issue.

**Comment by TurretedAsh** [comment]
Thank you for that <3
