### ISSUE TITLE
Removing the default line throws IndexOutOfBoundsException 

### ISSUE THREAD

**Issue by EpicKnarvik97** [DecentSoftware-eu/DecentHolograms#144]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms
2. Create a new hologram named `test`
3. Run /dh line rem test 1 1
4. Internal error message is displayed in chat, and a stack trace is shown in the console.

### Solution

It seems the problem causes an IndexOutOfBoundsException related to removing the first page. You should probably check that the index is in bounds when removing from the pages array.

### Server Version

Paper 1.19.4 550

### Client Version

1.20.1

### Plugin Version

2.8.3

### Log

https://pastebin.com/H5ZkhGYH

**Comment by Andre601** [comment]
Well.... what did you do?

**Comment by EpicKnarvik97** [comment]
> Well.... what did you do?

As specified in reproduction, I created a new hologram and deleted the default line (page 1 line 1). The deletion of the line itself seems to work fine, but for some reason, the plugin wants to remove page 2 (`eu.decentsoftware.holograms.api.holograms.Hologram.removePage(Hologram.java:915)`) as well, without there being a page 2, which causes `java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1`.

**Comment by EpicKnarvik97** [comment]
Okay, I tested a bit more, and generally, it seems that whenever a page is removed because all lines for that page are removed, the index used for triggering page deletion is 1-indexed instead of 0-indexed. This does not happen when the page is removed directly using `/dh page rem`.
