### ISSUE TITLE
No name Hologram

### ISSUE THREAD

**Issue by Dominilk01** [DecentSoftware-eu/DecentHolograms#146]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

I want add buch of Holograms but i need to name all of each,
and affter creating i don't actualy modify them

### Feature

Create Hologram but with no name

this mean on thore holograms will not be list in CACHED_HOLOGRAMS;

### Alternatives

idk

**Comment by Andre601** [comment]
If you use the API, just randomly generate a name using something like `UUID.randomUUID().toString()` or `String.valueOf(System.currentTimeMillis())`

**Comment by Dominilk01** [comment]
yes but i still think its not so coplicate to add and make a feature,
but thanks for idea

**Comment by Andre601** [comment]
The question here is, what is the overall benefit, if any, over the solution I just mentioned?

Personally speaking, adding a method just to not having to deal with a single input - which can be solved with the above ideas - seems like bloat to me.

**Comment by Dominilk01** [comment]
If you want say that my proposition trash say it
