### ISSUE TITLE
API for hiding and showing holos is bugged

### ISSUE THREAD

**Issue by JHarris12345** [DecentSoftware-eu/DecentHolograms#151]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

I am creating holograms and trying to hide them from a player. I use:

        dHologram.setDefaultVisibleState(true);
        dHologram.setHidePlayer(player);

Yet this hides them for about a second before showing them again. I think this also causes another issue I have where I create holograms that are FALSE default visibility and show them to players but everyone else can see them pop up briefly too despite not being shown to them

### Server Version

1.17.1

### Client Version

1.20.1

### Plugin Version

2.8.3

### Log

No errors in the logs

**Comment by d0by1** [comment]
Hello, could you please share more of your code, specifically how you created the hologram and where you applied the visibility settings?
