### ISSUE TITLE
Cannot use decimal numbers on location

### ISSUE THREAD

**Issue by Nino1500** [DecentSoftware-eu/DecentHolograms#153]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms...
2. Use the API
3. set decimal numbers on location Y-Coord
4. find out it doesnt work and only whole numbers work

### Server Version

1.20.1

### Client Version

1.20.1

### Plugin Version

2.8.3

### Log

Theres no crash or indication on an error

**Comment by Andre601** [comment]
Please provide a reproduction example

**Comment by Nino1500** [comment]
Make a holo with and without decimals, thats actually the reproduction
![reproduction](https://github.com/DecentSoftware-eu/DecentHolograms/assets/29626853/c35beed0-6cfc-4276-8924-778a0cf02108)

**Comment by Andre601** [comment]
You call `Location#toCenterLocation()`

Pretty sure that one forces Y to end up on a whole number...
