### ISSUE TITLE
DecentHolograms sometimes disappearing when switching servers quickly

### ISSUE THREAD

**Issue by KhrysAK47** [DecentSoftware-eu/DecentHolograms#16]
Hello there, I'm using latest version of DH and a issue I encountered twice in a span of a week is that holograms sometimes disappear if switching servers quickly (joining the specific server that has DH holograms installed). I have no guaranteed way of replicating the issue but is there a possibility to somehow make a forced check for that? The server is running on BungeeCord, using latest version of DH. (The DH is used in server, not in bungee - of course).

The holograms fix after doing /dh reload.

**Comment by d0by1** [comment]
Hello, I've noticed this bug before and thought that it was fixed already. I will look into it, thanks for reporting it!

**Comment by FootClick** [comment]
me too

**Comment by d0by1** [comment]
If this still happens it won't be fixed in the current version. This issue along with many others will be resolved in an upcoming 3.0 rewrite of the plugin. I will close this issue now as there is nothing else to discuss.
