### ISSUE TITLE
Custom Inventories / Renamed Chests spawn hologram with custom name above chest

### ISSUE THREAD

**Issue by JanQuintus** [DecentSoftware-eu/DecentHolograms#162]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Rename a chest / Open a custom inventory (e.g. plugin)
2. Close chest / inventory

[Example 1](https://imgur.com/O020Kuz)
[Example 2](https://imgur.com/a/QyQz9JS)

### Server Version

1.20.2

### Client Version

1.20.2

### Plugin Version

2.8.4

### Log

-

**Comment by Andre601** [comment]
What makes you think this is actually an issue caused by DecentHolograms and not any other plugin?

**Comment by JanQuintus** [comment]
That's what you get when you don't go through all the possibilities.... As it turns out, it's not DH, the display of names over renamed boxes is a standard feature since the anvil was introduced. 

I'm sorry, we are updating our old server and just recently switched from HD to DH, before that we didn't notice the "problem", hence the assumption it was DH.
