### ISSUE TITLE
When allowing placeholders within animations, formatting code within gradients will have no effect.

### ISSUE THREAD

**Issue by XXY233** [DecentSoftware-eu/DecentHolograms#163]
animation.yml:
```
speed: 50
pause: 50
steps:
- '<#B22AFE>&n&lTEST</#FFFF00>'
```

---

![92dd5e7e83ff6fb239ac062b7260a7ab](https://github.com/DecentSoftware-eu/DecentHolograms3/assets/46647646/381de700-928b-4491-863b-9304841e0c1d)
```
allow-placeholders-inside-animations: true
```

---

![289ac3b456610bc93b13da31203d1642](https://github.com/DecentSoftware-eu/DecentHolograms3/assets/46647646/5c235a7e-3544-4f35-8033-31211cad88dd)
```
allow-placeholders-inside-animations: false
```

**Comment by Andre601** [comment]
Checking the code, I can't see anything that would cause the issue you describe here:
https://github.com/DecentSoftware-eu/DecentHolograms/blob/main/src/main/java/eu/decentsoftware/holograms/api/holograms/HologramLine.java#L314-L322

All DH does is parse the line by replacing specific internal placeholders and also send it to PAPI to parse, if that plugin is enabled:
https://github.com/DecentSoftware-eu/DecentHolograms/blob/main/src/main/java/eu/decentsoftware/holograms/api/holograms/HologramLine.java#L338-L356

Nothing there suggests that it strips away colours...
My best guess is, that PAPI causes this removal of colours, as this was a bug with it iirc, which should've been fixed already. So make sure you actually use the latest version of PAPI and DH.

**Comment by XXY233** [comment]
Thank you! This issue has been fixed after I updated the PlacehplderAPI from 2.11.1 to 2.11.5.
