### ISSUE TITLE
'Do you have DecentHolograms plugin installed?' Wouldn't you always have the plugin installed in this scenario?

### ISSUE THREAD

**Issue by jakepronger** [DecentSoftware-eu/DecentHolograms#168]
https://github.com/DecentSoftware-eu/DecentHolograms/blob/673e45c724910021d47f23257845c659cb60db17/src/main/java/eu/decentsoftware/holograms/api/DecentHologramsAPI.java#L97

**Comment by d0by1** [comment]
You would not. Why is this an issue?

**Comment by jakepronger** [comment]
Understood!
