### ISSUE TITLE
java.lang.NoClassDefFoundError: eu.decentsoftware.holograms.api.DHAPI

### ISSUE THREAD

**Issue by ambit741235WHJR** [DecentSoftware-eu/DecentHolograms#171]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Added JitPack Repo and DecentHolograms API to `pom.yml`
2. Updated the maven project
3. Build the plugin
4. Execution causes this error

### Solution

I don't know about this but maybe this will help
![image](https://github.com/DecentSoftware-eu/DecentHolograms/assets/100905193/a450c3a5-e196-463a-8e1f-82479764fb21)

### Server Version

git-Purpur-2062 (MC: 1.20.1)

### Client Version

1.20.1

### Plugin Version

2.8.5

### Log

https://pastebin.com/hMSKWm7C

**Comment by Andre601** [comment]
Make sure you added `<scope>provided</scope>` to the decent holograms dependency and that you defined it as (soft)dependency to your plugin.yml

**Comment by ambit741235WHJR** [comment]
It's fixed now, thanks. Dependency was the problem.
