### ISSUE TITLE
Players using riptide crash into armor stands

### ISSUE THREAD

**Issue by cunhar** [DecentSoftware-eu/DecentHolograms#174]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

Try to use riptide in rain on in water wilst the green health + signs are visible. 

The player then crashes into the armorstands

### Server Version

1.20.2 - purpur

### Client Version

vanilla 1.20.2

### Plugin Version

 2.8.5

### Log

nothin in logs

**Comment by d0by1** [comment]
This honestly seems like a client issue and not something we can fix in a plugin.

**Comment by d0by1** [comment]
I will now close this issue as this can't be fixed.
