### ISSUE TITLE
ICONs not updating when using placeholder

### ISSUE THREAD

**Issue by kristouffe** [DecentSoftware-eu/DecentHolograms#176]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

Hi,

I wanted to make a dynamic Shop with DC using floating items and placeholders like

`#ICON:%player_item_in_hand%`

This should change when I change my in hand item. But it doesn't, it stays the same (the first item I had in hand).
Once I reload the plugin it changes with the item I have in hand. but it stays static again.

Using the exact same placeholder as text, makes it dynamic, but ICON stays static.
I also tried different placeholders from different plugins, it's all the same result.

Is that a bug somehow? Or did I just do something wrong?
It works well with other plugins, so I expected it to work with DH aswell.

https://github.com/DecentSoftware-eu/DecentHolograms/assets/39053190/d7aaf632-3de4-44ab-83de-2ddf9f9f6347

Thanks

### Server Version

This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7) You are running the latest version

### Client Version

1.20.2

### Plugin Version

This server is running DecentHolograms v2.8.5 by d0by : https://www.spigotmc.org/resources/96927/

### Log

no error in console, just a strange behaviour from DH

**Comment by Andre601** [comment]
This is my personal guess here, but I believe DH intentionally doesn't update the item at an interval... Most likely because it would cause constant despawns and respawns of the item itself, which if a desync or similar happens could cause duplicate items to manifest which in the end could lag out the client if it happens too many times.

**Comment by d0by1** [comment]
Hello, placeholders will now work in Icon lines since version 2.8.7.
