### ISSUE TITLE
DecentHolograms incompatible with future Paper versions

### ISSUE THREAD

**Issue by kennytv** [DecentSoftware-eu/DecentHolograms#186]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

Run https://github.com/PaperMC/testing/releases/tag/no-relocation, start with DecentHolograms

### Solution

See https://forums.papermc.io/threads/paper-velocity-1-20-4.998/#post-2955

### Server Version

1.20.4

### Client Version

1.20.4

### Plugin Version

2.8.6

### Log

https://paste.gg/p/anonymous/4ea996af04484343b25fc55ba1c368e5

**Comment by Andre601** [comment]
Looking at the code, the only problem I can see is updating the Version class... This *could* be relatively simple, but may require to find out every possible output of `Bukkit.getServer().getBukkitVersion()` down to 1.8 to create proper changes to use as it seems to be a `get package name -> check with enum of version patterns` thing used here.

Perhaps getting the Bukkit version, doing some string transformations (i.e. split at - and use first part and replace dots with _) could already go a long way here... But again would we need to know all versions that the plugin should support and their respecive Bukkit version output... :/

**Comment by d0by1** [comment]
Hello, a workaround has been implemented in version 2.8.7. Thank you for letting us know about this!
