### ISSUE TITLE
It possible to integrate link URL clickable with DecentHologram ? ex : youtube link:https://www.youtube.com/watch?v=qN1ZaFtIBuI&t=916s

### ISSUE THREAD

**Issue by PatalkokGIT** [DecentSoftware-eu/DecentHolograms#187]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

I would like players in certain locations to be able, for example, to access a tutorial on YouTube by clicking on a hologram (action).

Additionally, for other information, provide a link to Discord for documentation or to report a bug, etc.

### Feature

you can define action for exemple   actions: {link} for specific hologram

### Alternatives

It would also be possible by doing '...'

**Comment by d0by1** [comment]
That is impossible. The most you can do is use the MESSAGE action and let the player click the link in chat.
