### ISSUE TITLE
add option background

### ISSUE THREAD

**Issue by stormkiller0** [DecentSoftware-eu/DecentHolograms#189]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [ ] I made sure, that this feature has not been requested yet.

### Problem

add background option like in Fancy Holograms

### Feature

add background option like in Fancy Holograms

### Alternatives

add background option like in Fancy Holograms

**Comment by Andre601** [comment]
This is impossible.
DH does not use text display entities.
