### ISSUE TITLE
When a player joins the server several errors are thrown from Decent Holograms. 

### ISSUE THREAD

**Issue by lorentedford** [DecentSoftware-eu/DecentHolograms#194]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms...
2. Server is one of many in  a network of servers.
3. Join Server.
4. This happens please look below...

```
UUID of player lorentedford is 2e805087-ecf9-44d5-823b-9a55ad073801
Server thread/WARN10:35:53
[PremiumVanish]: Packet-based advancement interception is not supported on your server version, it is recommended to use PaperSpigot for API-based interception. (Field index 0 is out of bounds for length 0)
[DecentHolograms]: Failed to modify player's pipeline. (lorentedford)
Console10:35:53
java.lang.NullPointerException: Cannot invoke "eu.decentsoftware.holograms.api.utils.reflect.ReflectField.getValue(Object)" because "eu.decentsoftware.holograms.api.nms.NMS.PLAYER_CONNECTION_NETWORK_MANAGER_FIELD" is null
at eu.decentsoftware.holograms.api.nms.NMS.getPipeline(NMS.java:250) ~[?:?]
at eu.decentsoftware.holograms.api.nms.PacketListener.executeOnPipeline(PacketListener.java:51) ~[?:?]
at eu.decentsoftware.holograms.api.nms.PacketListener.hook(PacketListener.java:29) ~[?:?]
at eu.decentsoftware.holograms.api.listeners.PlayerListener.onJoin(PlayerListener.java:28) ~[?:?]
at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.players.PlayerList.a(PlayerList.java:295) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4054-Spigot-e9ec548-619936d]
at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.a(ServerConfigurationPacketListenerImpl.java:129) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4054-Spigot-e9ec548-619936d]
at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(SourceFile:20) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4054-Spigot-e9ec548-619936d]
at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(SourceFile:7) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4054-Spigot-e9ec548-619936d]
at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:33) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4054-Spigot-e9ec548-619936d]



at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4054-Spigot-e9ec548-619936d]
at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4054-Spigot-e9ec548-619936d]
at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4054-Spigot-e9ec548-619936d]
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1191) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4054-Spigot-e9ec548-619936d]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4054-Spigot-e9ec548-619936d]
at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4054-Spigot-e9ec548-619936d]
at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1170) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4054-Spigot-e9ec548-619936d]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1163) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4054-Spigot-e9ec548-619936d]
at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4054-Spigot-e9ec548-619936d]
at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1147) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4054-Spigot-e9ec548-619936d]
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1060) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4054-Spigot-e9ec548-619936d]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4054-Spigot-e9ec548-619936d]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Server Version

This server is running CraftBukkit version 4054-Spigot-e9ec548-619936d (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) Checking version, please wait...  You are running the latest version

### Client Version

1.20.4

### Plugin Version

This server is running DecentHolograms v2.8.6 by d0by : https://www.spigotmc.org/resources/96927/

### Log

https://pastebin.com/0j1RQi06

**Comment by Andre601** [comment]
Known issue. Unknown fix.

**Comment by lorentedford** [comment]
I am total crap at understanding programming or coding but I put this into copilot to see what it would say and this is what it responded with I hope this helps fix this plugin.


The `NullPointerException` you're encountering with the **DecentHolograms** plugin is a known issue that has been reported by several users. This particular error is caused when the plugin attempts to access a player's network manager field, which is null. This can happen due to various reasons such as compatibility issues with other plugins, incorrect server setup, or a bug within the DecentHolograms plugin itself.

Here are some steps you can take to try and resolve this issue:

1. **Update the Plugin**: Make sure you are using the latest version of the DecentHolograms plugin that is compatible with your server's version of Minecraft.

2. **Check for Compatibility**: Ensure that there are no compatibility issues with other plugins, especially those that handle packets or modify the player's pipeline.

3. **Review Configuration**: Look through the plugin's configuration files for any incorrect settings that might be causing the issue.

4. **Seek Support**: Visit the plugin's [GitHub issues page](^7^) or [SpigotMC discussion thread](^2^) to see if others have encountered and resolved similar issues. You can also post your problem there to get help from the community or the plugin developers.

5. **Server Logs**: Check your server logs for any additional information that might indicate what is causing the `PLAYER_CONNECTION_NETWORK_MANAGER_FIELD` to be null.

6. **Plugin Dependencies**: Make sure all dependencies required by the DecentHolograms plugin are installed and up to date.

If after trying these steps the issue persists, it would be best to report it to the plugin developers with detailed information about your server setup and the error logs. They might be able to provide a more specific solution or release a patch to fix the bug.

Source: Conversation with Bing, 4/13/2024
(1) java.lang.NullPointerException: Cannot invoke "eu ... - GitHub. https://github.com/DecentSoftware-eu/DecentHolograms/issues/158.
(2) Spigot - DecentHolograms | 1.8 - 1.20.4 | PAPI Support | No .... https://www.spigotmc.org/threads/decentholograms-1-8-1-20-4-papi-support-no-dependencies.530078/page-13.
(3) Errors generated when players join in large numbers #125 - GitHub. https://github.com/DecentSoftware-eu/DecentHolograms/issues/125.
(4) [DecentHolograms] Failed to modify player's pipeline. (℡Shugayip)java .... https://pastebin.com/REAPJXg0.
(5) DecentHolograms | 1.8 - 1.20.4 | PAPI Support | No ... - SpigotMC. https://www.spigotmc.org/resources/decentholograms-1-8-1-20-4-papi-support-no-dependencies.96927/updates.
(6) DecentHolograms ERROR 1.20.4 - Pastebin.com. https://pastebin.com/EyyBBNCa.
(7) undefined. https://github.com/resi23/DecentHolograms/releases/tag/2.8.6.
(8) When a player joins the server several errors are thrown from Decent .... https://github.com/DecentSoftware-eu/DecentHolograms/issues/194.
(9) Issues · DecentSoftware-eu/DecentHolograms · GitHub. https://github.com/DecentSoftware-eu/DecentHolograms/issues/.

**Comment by lorentedford** [comment]
Here is a follow up on that player connection null thing all stuff I never will understand.

The issue with `PLAYER_CONNECTION_NETWORK_MANAGER_FIELD` being null in Spigot 1.20.4 seems to be related to the reflection code that plugins use to interact with the Minecraft server's underlying code (NMS). When Spigot updates, the field names and class structures can change, which often leads to reflection code breaking.

Here's a general approach to fix this issue:

1. **Update the Plugin**: Ensure that you're using the latest version of the plugin that's compatible with Spigot 1.20.4. Plugin developers usually update their plugins to work with the latest versions of Spigot.

2. **Check for Compatibility Issues**: Make sure there are no compatibility issues with other plugins. Sometimes, one plugin can interfere with the workings of another, especially if they both use reflection to access NMS code.

3. **Review the Plugin Code**: If you have access to the plugin's source code, review the code where the `PLAYER_CONNECTION_NETWORK_MANAGER_FIELD` is accessed. You may need to update the field name to match the one used in Spigot 1.20.4.

4. **Community Support**: Look for solutions on community forums like [SpigotMC](^1^). Other developers might have encountered similar issues and could have shared solutions.

5. **Use a Different Approach**: If reflection is causing too many issues, consider using Spigot's API or other stable APIs that provide the functionality you need without directly accessing NMS code.

6. **Debugging**: Use debugging tools to trace back the error and find out why the field is null. This might give you more insight into what's going wrong.

7. **Seek Expert Help**: If you're not familiar with NMS or reflection, it might be worth reaching out to a developer who is. They can provide valuable assistance and potentially fix the issue for you.

Remember to always back up your server before making any changes to avoid data loss. If you're not comfortable making these changes yourself, it's best to consult with a professional.

Source: Conversation with Bing, 4/13/2024
(1) Solved (1.20.4) Define "connection.channel" field of NPC connection. https://www.spigotmc.org/threads/1-20-4-define-connection-channel-field-of-npc-connection.631724/.
(2) Solved Unable to set player scoreboard with player#setscoreboard - [SpigotMC](https://www.spigotmc.org/threads/1-20-4-define-connection-channel-field-of-npc-connection.631724/). https://www.spigotmc.org/threads/unable-to-set-player-scoreboard-with-player-setscoreboard.509811/.
(3) java.lang.NullPointerException: Cannot invoke "eu ... - GitHub. https://github.com/DecentSoftware-eu/DecentHolograms/issues/158.
(4) 1.20 - Make a fake player | SpigotMC - High Performance Minecraft. https://www.spigotmc.org/threads/make-a-fake-player.621790/.
(5) undefined. https://github.com/CitizensDev/Citi...pcs/nms/v1_20_R3/network/EmptyConnection.java.
(6) undefined. https://github.com/CitizensDev/Citi.../java/net/citizensnpcs/util/EmptyChannel.java.
(7) undefined. https://www.spigotmc.org/threads/creating-a-scoreboard.156548/.

**Comment by Andre601** [comment]
@lorentedford Your second comment is pretty much a repeat of your first, especially in terms of suggested steps to try and fix this.

The error itself is still a relatively difficult thing to solf as we still can't find the exact cause here.

One common thing people report however, is that this error seems to appear more frequently on Spigot servers, because when they switch to Paper is the error gone for most of them.
So the issue could be some code changes within Spigot or other kind of problem...

**Comment by lorentedford** [comment]
Hmm ok so are you Building this plug in for paper then exclusively?

**Comment by Andre601** [comment]
> Hmm ok so are you Building this plug in for paper then exclusively?

No.
Where was that even mentioned?

It's just that it seems likely that something in Spigot changed (That it probably messes with some internals that paper doesn't) that now breaks compat in DH...
But again, it's hard to find the exact cause of this error, as there can be various reasons. From timing (Player joining and leaving fast) to other plugins messing with the internals...

**Comment by lorentedford** [comment]
> > Hmm ok so are you Building this plug in for paper then exclusively?
> 
> No. Where was that even mentioned?
> 
> It's just that it seems likely that something in Spigot changed (That it probably messes with some internals that paper doesn't) that now breaks compat in DH... But again, it's hard to find the exact cause of this error, as there can be various reasons. From timing (Player joining and leaving fast) to other plugins messing with the internals...

Well I asked this because some times developers claim its for spigot but then they use like a third party api to pull from. Basically trying to code for one but then leaving the other out to dry. I have run into this in the IT environment in some mission critical equipment and it sucks.. Please do keep working on this I hope some day we can get it running smoothly again. I wish I new how to code I would roll up my sleeves and help if I could. With my Neurological crap I am so lost it isn't even funny..

**Comment by d0by1** [comment]
I will now close this issue to streamline the issue tracker. If you witness the problem again, feel free to create a new issue. I did make some changes to this in 2.8.7 and it might already be fixed.
