### ISSUE TITLE
Sub Permissions for Commands

### ISSUE THREAD

**Issue by Hatzefatz** [DecentSoftware-eu/DecentHolograms#195]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

I think it would be useful to have single sub permissions per command

### Feature

I would like to see differend subpermission for commands

**Comment by Andre601** [comment]
Made a PR that should address this: #196
