### ISSUE TITLE
Cannot use DHAPI

### ISSUE THREAD

**Issue by Pelfox** [DecentSoftware-eu/DecentHolograms#20]
I'm trying to create a new hologram, but keep getting this error
`java.lang.NoClassDefFoundError: Could not initialize class eu.decentsoftware.holograms.api.holograms.Hologram`.
This is my code:
```java
Hologram campfireHologram = DHAPI.createHologram("campfire-hologram", ConfigUtils.campfireHologramLocation(world), List.of(String.format(ConfigUtils.remainingBurnTime(), this.formatSeconds(ConfigUtils.startBurnTime()))));
```

**Comment by lukasjakobi** [comment]
Try to add `<scope>provided</scope>` to the maven dependency of the DecentHolograms API. Also make sure you add the JAR-file of DecentHolograms in your plugin folder. This worked in my case.
