### ISSUE TITLE
Custom replacemente on API

### ISSUE THREAD

**Issue by guikaua12** [DecentSoftware-eu/DecentHolograms#200]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

Is it possible to do something like this?

```java
api.registerIndividualPlaceholder("joust_rank", 20, (player, placeholder) -> {
    final JoustUser user = userCache.get(player.getName());

    if (user == null) return "";

    return NumberUtils.format(user.getLeaderboardPosition().getPosition());
});
```

### Feature

Way to register custom placeholders

### Alternatives

It would also be possible by doing '...'

**Comment by Andre601** [comment]
Make a placeholder for PlaceholderAPI.
The benefit of that method is that other plugins supporting PlaceholderAPI can use it too.

- [How to use PlaceholderAPI](https://wiki.placeholderapi.com/developers/using-placeholderapi/)
- [How to make placeholders for PlaceholderAPI](https://wiki.placeholderapi.com/developers/creating-a-placeholderexpansion/)

**Comment by Dominilk01** [comment]
PlaceholderAPI alredy has a way to create custom place holder ¯\_(ツ)_/¯
