### ISSUE TITLE
Incorrect method call

### ISSUE THREAD

**Issue by bridgelol** [DecentSoftware-eu/DecentHolograms#203]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms...
2. Set item using api
3. Get this error

![image](https://github.com/DecentSoftware-eu/DecentHolograms/assets/29434554/85b71ae0-e48b-41bf-bc44-6af49e311dc0)

### Server Version

1.20.4

### Client Version

1.20.4

### Plugin Version

2.8.6

### Log

https://paste.helpch.at/utopejosev.css

**Comment by Andre601** [comment]
There is a fix in the more recent commits for this. You'll have to wait for an update.
