### ISSUE TITLE
Allays always generate +1 hp holograms

### ISSUE THREAD

**Issue by rudde0** [DecentSoftware-eu/DecentHolograms#208]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Enable damage-display.enabled to true
2. Spawn an allay
3. This allay will always generate +1 hologram whether regain heal or not.
![image](https://github.com/DecentSoftware-eu/DecentHolograms/assets/26517681/cdee7388-261e-438f-9d28-5e04d802428b)

### Server Version

Purpur 1.20.4 (b2169)

### Client Version

1.20.4 (Fabric)

### Plugin Version

2.8.6

### Log

No console error

**Comment by d0by1** [comment]
Hello, this has been fixed in version 2.8.7. Thank you for reporting it!
