### ISSUE TITLE
#HEAD items uncentered?

### ISSUE THREAD

**Issue by em-kaa** [DecentSoftware-eu/DecentHolograms#211]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms...
2. Create a hologram with a #HEAD line...
3. Using blocks will make them centered, but using items (like an axe) will make them uncentered.

![image](https://github.com/DecentSoftware-eu/DecentHolograms/assets/142349883/39273418-0e7a-4bfe-9d67-fa7e0667ca7f)

![image](https://github.com/DecentSoftware-eu/DecentHolograms/assets/142349883/834dabd5-c70a-4cc2-be3c-897e85f215fb)

### Server Version

1.20.4

### Client Version

1.20.4

### Plugin Version

2.8.6

### Log

not needed...

**Comment by Andre601** [comment]
This is intended behaviour.
The itm is just added to the head slot of the invible armor stand.

If you want it centered, use the offsetx and offsetz commands for the line.

**Comment by Andre601** [comment]
In a normal situation would the items not change anyways.

If you want centered items, use the `#ICON` type or live with the offset.

**Comment by em-kaa** [comment]
> In a normal situation would the items not change anyways.
> 
> If you want centered items, use the `#ICON` type or live with the offset.

but then the icons don't update 😭

**Comment by Andre601** [comment]
They usually don't on heads either. Again, this is an issue you have to live with as it's nothing that can be fixed, given that this is how items in the head slot are rendered.

**Comment by em-kaa** [comment]
:(
