### ISSUE TITLE
DH throwing error with Holograms used in BetonQuest

### ISSUE THREAD

**Issue by kristouffe** [DecentSoftware-eu/DecentHolograms#215]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms...
2. Connect next to holograms used in BetonQuest
3. I have no other hologram in DecentHologram for now, everything comes from BQ.

Don't know if this is on your end or on BQ's end?

### Server Version

1.20.6

### Client Version

1.20.6

### Plugin Version

This server is running DecentHolograms v2.8.8 by d0by : https://www.spigotmc.org/resources/96927/

### Log

https://pastebin.com/41WPax99

**Comment by r5t0neer** [comment]
I fixed it by editing code, in HologramItem class this.nbt cannot include '{' and '}', and nbt must be full, i.e. include material - {material[properties=123]}

**Comment by d0by1** [comment]
Hi, Item NBT is now supported in Minecraft 1.20.5+ as of DH version 2.8.10.
