### ISSUE TITLE
Hello, can you update it to support creating holograms using Chinese? I am a user from China.

### ISSUE THREAD

**Issue by Suib6** [DecentSoftware-eu/DecentHolograms#216]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

Unable to efficiently carry out editing, as far as I am concerned

### Feature

Hello, can you update it to support creating holograms using Chinese? I am a user from China.

### Alternatives

It would also be possible by doing '...'

**Comment by d0by1** [comment]
I will now close this issue to streamline the issue tracker. If you wish to explain what the problem actually is and how we should resolve it, feel free to create another issue.
