### ISSUE TITLE
Item-NBT-API crash the maven api

### ISSUE THREAD

**Issue by PerrierBouteille** [DecentSoftware-eu/DecentHolograms#217]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Do a maven plugin
2. Import DecentHologram API
3. Try to build the project

Try with DecentHologram API 2.8.6 and 2.8.8

Error:
de.tr7zw:item-nbt-api:jar:2.12.2 was not found in https://hub.spigotmc.org/nexus/content/repositories/snapshots/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of spigotmc-repo has elapsed or updates are forced

Last version of Item-NBT-API: 2.13.0

### Solution

Just update the version of Item-NBT-API to 2.13.0 in the gradle config

### Server Version

Null (API)

### Client Version

Null (API)

### Plugin Version

2.8.6 and 2.8.8

### Log

In description

**Comment by Andre601** [comment]
Please [Read the Wiki](https://wiki.decentholograms.eu/api/get-started/).

It mentions this "issue" clearly, which btw is not a crash.
![grafik](https://github.com/DecentSoftware-eu/DecentHolograms/assets/11576465/59eff1d6-155c-4af2-8a14-58c6ea9db87a)

**Comment by PerrierBouteille** [comment]
I apply the repo before and that notworking but now after 1 hour that work idk why ;-; sry
