### ISSUE TITLE
Dependency not found

### ISSUE THREAD

**Issue by KampCikat** [DecentSoftware-eu/DecentHolograms#225]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

I am currently writing a plugin, but in the pom.xml i am unable to set the Dependency.
![Screenshot 2024-07-22 195949](https://github.com/user-attachments/assets/7ca9f16c-2365-4bd1-a112-c72e0d135d43)

I already added the jar file into the Modules and installed it locally ( <systemPath>${project.basedir}/libs/decentholograms-2.8.9.jar</systemPath>) but thats not the way i want it.

Im kinda new at this, so am i doing something wrong here?

### Server Version

1.21

### Client Version

1.21

### Plugin Version

2.8.9

### Log

https://pastebin.com/S9WuQnbn

**Comment by Andre601** [comment]
https://wiki.decentholograms.eu/api

**Comment by KampCikat** [comment]
https://pastebin.com/zhA2ZKYm help
