### ISSUE TITLE
transparent

### ISSUE THREAD

**Issue by Kocimietka7192** [DecentSoftware-eu/DecentHolograms#226]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

A nice addition would be if, decent holograms could increase and decrease the size of the font, and turn off the background, so called make a banner - as in the fancyhologram plugin

### Feature

example transparent on/off:
![image](https://github.com/user-attachments/assets/9960bcd9-d403-4e17-82e7-c46f292ed2ab) - this is off
![image](https://github.com/user-attachments/assets/7c6e8341-4a10-450a-af3e-cb998483694b) - this is on 

and:

![image](https://github.com/user-attachments/assets/7459d242-2815-4f62-9c36-57571eb6c786) - scale 1.5
![image](https://github.com/user-attachments/assets/9960bcd9-d403-4e17-82e7-c46f292ed2ab) - scale 1.0
 

### Alternatives

It would also be possible by doing '...'

**Comment by Andre601** [comment]
Those are all features of text display entities, which DecentHolograms does not support. And before you ask that: No, there is no ETA for when or even IF it will support those.

But as it stands right now is this an impossible feature for DH.

**Comment by Kocimietka7192** [comment]
Okay, I get it - in that case to be closed
