### ISSUE TITLE
Follow Entity API

### ISSUE THREAD

**Issue by rudde0** [DecentSoftware-eu/DecentHolograms#233]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

I want to make custom nametagged entities via DHAPI.

### Feature

Some hologram methods for custom nametag would be nice.
```
DHAPI#attachHologram(Entity entity, Hologram hologram);
DHAPI#unattachHolograms(Entity entity, Boolean destroyHologram);
DHAPI#unattachHologram(Entity entity, Hologram hologram, Boolean destroyHologram);
DHAPI#attachedHolograms(Entity entity);
```

**Comment by Andre601** [comment]
Just move the hologram to the NPC every 2nd tick or so? It's no rocket science and DH's main and only purpose is to offer holograms. Not to attach them to entities or similar, as that's already out of scope.

**Comment by rudde0** [comment]
Hologram interact is a feature also related with player interacts not with holograms but there is API for it.

I wanted to suggest it since "feature requests" button is open. I just kindly ask for it. If this is out of scope, they can close the topic.
