### ISSUE TITLE
1.21.1

### ISSUE THREAD

**Issue by jurohn** [DecentSoftware-eu/DecentHolograms#236]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1.21.1 isnt supported yet

### Server Version

1.21.1

### Client Version

1.21

### Plugin Version

Doesnt run. But ehmm... latest.

### Log

https://pastebin.com/q88yxL0K

**Comment by d0by1** [comment]
Support added in 2.8.11.

**Comment by jurohn** [comment]
> Support added in 2.8.11.

Fastest support ever. You won!
