### ISSUE TITLE
[Feature request] Compatibility to Head Database

### ISSUE THREAD

**Issue by sphings79** [DecentSoftware-eu/DecentHolograms#24]
Would be nice to have a compatibility to Head Database to use them in Holos.
https://www.spigotmc.org/resources/head-database.14280/

**Comment by Andre601** [comment]
This is already possible. Just use `HEADDATABASE_<id>` as the name of the head.

Example: `#ICON: PLAYER_HEAD (HEADDATABASE_1)`

**Comment by sphings79** [comment]
Sorry, didn't saw that in the wiki.
