### ISSUE TITLE
Using player heads with skull textures doesnt work anymore! #78 1.21.1 Paper

### ISSUE THREAD

**Issue by Dinos3396** [DecentSoftware-eu/DecentHolograms#244]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

To clerify this feature has been working for months on my server and it just now stopped working after this Paper 1.21.1 [#78](https://api.papermc.io/v2/projects/paper/versions/1.21.1/builds/78/downloads/paper-1.21.1-78.jar) update.

Install DH on a latest 1.21.1 paper server and set up a holo like this, it wont work and the head will appear as Steve.

`location: world_the_end:126.4:101.5:139.5
enabled: true
display-range: 64
update-range: 64
update-interval: 20
facing: 0.0
down-origin: true
pages:
- lines:
  - content: '<#ANIM:burn:&a,&2&l>Survival</#ANIM>'
    height: 0.30
    offsetX: 0.1
  - content: '&7%bungee_survival%/100'
    height: 0.30
    offsetX: 0.1
  - content: '#SMALLHEAD: PLAYER_HEAD (eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzY5MTk2YjMzMGM2Yjg5NjJmMjNhZDU2MjdmYjZlY2NlNDcyZWFmNWM5ZDQ0Zjc5MWY2NzA5YzdkMGY0ZGVjZSJ9fX0=)'
    height: 0.20
    offsetX: 0.1
  actions: 
    LEFT:
    - CONNECT:survival
    RIGHT:
    - CONNECT:survival`

### Server Version

1.21.1

### Client Version

1.21.1

### Plugin Version

2.8.11

### Log

https://mclo.gs/QxHoFQl

**Comment by Olzie-12** [comment]
Yep, it this [commit](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/8d52226914ce4b99f35be3d6954f35616d92476d#src/main/java/org/bukkit/craftbukkit/inventory/CraftMetaSkull.java) from spigot that broke it.

 I've made a PR #245

**Comment by d0by1** [comment]
This was fixed in 2.8.12.
