### ISSUE TITLE
[1.21.1] Can't get UUID / Head textures don't work

### ISSUE THREAD

**Issue by BakiDance** [DecentSoftware-eu/DecentHolograms#248]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

Holograms that use a custom head texture (whether be a texture value, or [offline] player name) fail to display the correct texture. A Steve head is shown instead, and the console is spammed with exceptions.

In previous versions, offline player heads still did not show (due to bug #230), but the console was not spammed with error messages, and using a texture value worked as intended. Using this version, not even texture values work.

I'm also using the [untested patch](https://github.com/DecentSoftware-eu/DecentHolograms/pull/245#issuecomment-2362497265) by Olzie, but that doesn't seem to result in any different behavior.

### Server Version

This server is running Paper version 1.21.1-119-master@7cd4f2c (2024-10-03T15:19:34Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT) You are running the latest version Previous version: git-Paper-496 (MC: 1.20.4)

### Client Version

1.21.1

### Plugin Version

2.8.11

### Log

https://paste.helpch.at/etaqidusew.rb

**Comment by martijnpu** [comment]
Hey,
The same issue appears at my servers after I updated to 1.21.1 (from 1.20.4)
Exact same error keeps spamming the console.

**Server Version**
This server is running Paper version 1.21.1-85-master@c5a1066 (2024-09-19T14:47:47Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

**Client Version**
1.21.1

**Plugin Version**
v2.8.11

**Comment by Technofied** [comment]
Same issue here.

**Comment by homerek111** [comment]
same issue, please fix

**Comment by Olzie-12** [comment]
https://github.com/DecentSoftware-eu/DecentHolograms/pull/245#issuecomment-2425229026 fixed.

**Comment by d0by1** [comment]
This was fixed in 2.8.12.
