### ISSUE TITLE
When 1.21.3?

### ISSUE THREAD

**Issue by Xenerain** [DecentSoftware-eu/DecentHolograms#252]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

Plugin not starting on version 1.21.3, when support for 1.21.3?

### Feature

1.21.3 support

### Alternatives

support 1.21.3

**Comment by Andre601** [comment]
Once someone finds time to implement support for it. Contributions are always welcome.

**Comment by d0by1** [comment]
Support for 1.21.3 was added in 2.8.12.

**Comment by SlimeDog** [comment]
Confirmed fixed with DH 2.8.12. Thank you.
