### ISSUE TITLE
Random Lag when any Hologram is in frame.

### ISSUE THREAD

**Issue by ShadowTech12** [DecentSoftware-eu/DecentHolograms#273]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Create any hologram 
2. Be within its rendering distance and sprint jump / fly in creative
3. When it loads / unloads there is a noticable hitch
4. Disabling all holograms resolves the issue

### Server Version

Paper 1.12.3-82

### Client Version

1.21.1

### Plugin Version

2.8.12

### Log

https://pastebin.com/WMKuNYnH

**Comment by Andre601** [comment]
This was reported before and pretty much confirmed to be a ViaVersion issue, as they fixed it in their recent releases.

Please test if it happens **on the same clent and server version** before reporting.

**Comment by ShadowTech12** [comment]
Updating Via Version / Backwards Fixed this issue. Thanks!
