### ISSUE TITLE
Placeholder request - error kick

### ISSUE THREAD

**Issue by daniel-skopek** [DecentSoftware-eu/DecentHolograms#274]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms...
2. Join to server

### Server Version

1.20.1

### Client Version

I will ask the player

### Plugin Version

2.8.12

### Log

https://pastebin.com/raw/D3vvwvhR

**Comment by Andre601** [comment]
Not aDH issue but an issue with a PlaceholderAPI placeholder.

Please **do not** report such issues to us.
Also, **always** fill out the complete issue template as requested.
