### ISSUE TITLE
First page in actions

### ISSUE THREAD

**Issue by q4h3x** [DecentSoftware-eu/DecentHolograms#34]
Hello, 
Iam trying to make a hologram with multiple lines, but when I want to make an action that will switch back to the first line i do 

"  actions:
    LEFT:
    - FIRST_PAGE "     ?
It does not work. Is there a way I can switch to the first line?

**Comment by Andre601** [comment]
`FIRST_PAGE` is not a supported Action.

https://wiki.decentholograms.eu/advanced/actions

Also, instead of manually configuring holograms - which I assume you do - should you use commands instead.

**Comment by d0by1** [comment]
"FIRST_PAGE" is not an action. Use PAGE:1 instead. I will mark this as resolved.
