### ISSUE TITLE
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached

### ISSUE THREAD

**Issue by PappoYT** [DecentSoftware-eu/DecentHolograms#36]
Today server shut down due to this error:
`[DecentHolograms Thread #1/WARN]: java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached`

Full error in log starting from line 20355:
[https://mclo.gs/M2SE7rk#L20355](https://mclo.gs/M2SE7rk#L20355)

**Comment by Andre601** [comment]
From the error you posted does this seem to not directly be an DH issue.
The stacktrace points to AJ leaderboards as the first case of a plugin, so it could be an issue on their end.
