### ISSUE TITLE
Placeholders not working inside animations

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [DecentSoftware-eu/DecentHolograms#37]
On Spigot 1.18.2 with DecentHolograms 2.3.1 if you set placeholder inside custom animation it doesnt change.

Also if you set line ex "%parkour_leaderboard_kosmos_<#ANIM:pa></#ANIM>%". where "pa" just rotates between numbers placeholder gets invalid.

**Comment by d0by1** [comment]
Placeholders are supported inside animation in the 2.5.0 release. I will now close this issue.
