### ISSUE TITLE
Bad timings

### ISSUE THREAD

**Issue by Rafalll1** [DecentSoftware-eu/DecentHolograms#47]
I have such timings, do know what the problem may be?
https://imgur.com/Cj59L2T

**Comment by Andre601** [comment]
1. Please provide the actual timings report and not just an image
2. Timings (v2) is not a reliable way to find the source of lag in your server. Please use a profiling plugin such as Lucko's Spark plugin to find the source of lag.

**Comment by d0by1** [comment]
Seems like no progress has been made here so I will close this issue now. If you want to continue this discussion, please create a new issue reporting your problem correctly.
