### ISSUE TITLE
HEad skin doed not Load (OfflinePLayer)

### ISSUE THREAD

**Issue by LxkasDEV** [DecentSoftware-eu/DecentHolograms#48]
(Player online)
![image](https://user-images.githubusercontent.com/63460419/167681820-79a5171f-e4de-4826-a8ab-b1bf5e66ab71.png)
(Player offline)
![image](https://user-images.githubusercontent.com/63460419/167681996-1b88af47-23f1-4d49-810c-8b2a0b3d5bcf.png)
Ass soon as the player does left, the head does unload

**Comment by Andre601** [comment]
Could you provide actual info about your server please?

- version?
- online or offline mode?
- used plugins?

**Comment by LxkasDEV** [comment]
Is is on offline mode, Part of an bungee (CloudNet). Server is running on 1.18

**Comment by Andre601** [comment]
My guess is that the head losing its texture is a (unwanted) downside of an offline-mode server, even while being part of a network...
I can't say for sure. Is the network in online mode?

**Comment by LxkasDEV** [comment]
The network is in online mode. 
But i also noticed, everytime the holo updates, the texture loads and undloads a second later

**Comment by Andre601** [comment]
> The network is in online mode. But i also noticed, everytime the holo updates, the texture loads and undloads a second later

Could be a network issue or perhaps just a general downside of a server being part of a server network. I can't say for sure.

**Comment by LxkasDEV** [comment]
Yes i tested it on an localhost in online mode. I also think the problem is the offline mode of the server... But i dont know a fix for this. Could this be a problem with Paper? You got an idea?

**Comment by d0by1** [comment]
I believe this issue is not related to DH. I will close it now.
