### ISSUE TITLE
PAPI Spam

### ISSUE THREAD

**Issue by VerklicktTV** [DecentSoftware-eu/DecentHolograms#51]
Hello!
I realised that DecentHolograms asks for Placeholders alltime, which can cause lag. Is it possible to put a short delay between the requests for Placeholders from PAPI, so the Server could chill a bit?

Thanks 
Verklickt

**Comment by Andre601** [comment]
You usually are able to set an update delay for a hologram, but because of a bug is that update delay ignored.
A PR to fix this is already made: https://github.com/DecentSoftware-eu/DecentHolograms/pull/43

**Comment by VerklicktTV** [comment]
> 

Cool, thanks

**Comment by d0by1** [comment]
This has been fixed.
