### ISSUE TITLE
Suggestion: Hiding armorstand in GM3 or making the entity configurable

### ISSUE THREAD

**Issue by Mangonels** [DecentSoftware-eu/DecentHolograms#53]
I know there's no actual entity and that a packet is sent, however, currently, all holograms are based on an armorstand.

In GM3 this armorstand is visible, and it visually breaks some concepts I had in mind.

Making another entity configurable for this would be useful (I could personally just set it to ambient particle or something really small and imperceptible). I doubt making the armorstand invisible in GM3 is an option though?

**Comment by Andre601** [comment]
Armor stands ARE invisible... That's why you can't see them in survival, adventure or creative mode.
Hiding them in spectator would mean that they are completely gone too.

Regarding particles (I assume you mean that lingering potion entity thing?): They afaik aren't permanent unlike armor stands, meaning they would need to be refreshed in regular intervals.
Also, they may or may not emit/display particles. Not sure about those things tho.

**Comment by Mangonels** [comment]
I understand what you are saying perfectly, and know this is complicated.

That is why my alternate (half way) proposal is making the entity configurable.

I'm asuming it can be done, but I also asume there's a chance that on changing the entity, some other plugin features could break.

**Comment by d0by1** [comment]
The problem with particles or any other entities is the click detection. Armor stands are just the perfect entity to use for now basically.

**Comment by Andre601** [comment]
> The problem with particles or any other entities is the click detection. Armor stands are just the perfect entity to use for now.

Well, there is an alternative which would be slime as it could be resized and allow a larger hitbox to interact with... Tho it could have some downsides I'm not aware of.

**Comment by Mangonels** [comment]
Indeed, I've seen other plugins doing click detection with armorstands and it tends to be confusing since the players don't know the hitbox is centered and small. Using other entites would ineed improve collision detection, so that's a plus in my oppinion.

**Comment by Mangonels** [comment]
This feature doesn't seem to be referenced yet in the wiki
