### ISSUE TITLE
Unable to move holograms to ~0.x height Y 

### ISSUE THREAD

**Issue by TypicalShavonne** [DecentSoftware-eu/DecentHolograms#60]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

I wanted to use holograms as an NPC nametag to show servers player
but DecentHolograms unable to move the holograms to Y=~0.5

### Feature

beable to move holograms to 0.x

### Alternatives

i saw Gholo and holographic could do this and why not DH too

**Comment by Andre601** [comment]
Could you actually explain what you tried to do?

"but DecentHolograms unable to move the holograms to Y=~0.5" doesn't tell us anything tbh

**Comment by TypicalShavonne** [comment]
like, i have a hologram at y:60, and i cant do move it to y:60.5

**Comment by d0by1** [comment]
Fixed in version 2.5.4, thanks for reporting.
