### ISSUE TITLE
DecentHolograms undo

### ISSUE THREAD

**Issue by FootClick** [DecentSoftware-eu/DecentHolograms#62]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

/DecentHolograms movehere

Easy move wrong

### Feature

like some plugins undo command

**Comment by Andre601** [comment]
Just move to the previous location and use the same command?

A undo command would require the plugin to keep track of changes, which may increase RAM and/or CPU usage which isn't good.

**Comment by FootClick** [comment]
> Just move to the previous location and use the same command?
> 
> A undo command would require the plugin to keep track of changes, which may increase RAM and/or CPU usage which isn't good.

okay
