### ISSUE TITLE
Strange bug in combat

### ISSUE THREAD

**Issue by alechretien16** [DecentSoftware-eu/DecentHolograms#63]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

Hello!
I have a problem with DecentHolograms, with the latest version as strange as it may seem, on my purple survival server 1.19.2 combat functions such as the "sweeping edge" enchantment, critical hits, and sword area damage do not work!
I'm not sure what causes it, but it only works properly if I remove all plugins and leave only decentholograms.

### Server Version

Purpur #1759 - 1.19.2

### Client Version

1.19.2

### Plugin Version

2.5.3

### Log

¡Sorry, not error in console!

**Comment by Andre601** [comment]
If it only works with DH, doesn't that mean another plugin causes this issue?

Also, this issue has been discussed on the Discord server yesterday where I contacted the Purpur devs and they said there could be two causes:

- ProtocolLib - Fix by up/downgrading it
- One of the patches and settings, explained here: https://purpurmc.org/docs/Configuration/allow-unsafe-enchants

**Comment by Quaintified** [comment]
I am also having this issue. I have taken out ProtocolLib (so it's not that). And I'm running on the latest Paper 1.19.2 (build 125).

It has **only** been happening since I installed the update to the plugin that happened yesterday. And, yes, I have had DecentHolograms on my server before the update yesterday.

**Comment by Quaintified** [comment]
Just did some more testing... It seems it is conflicting with LibsDisguises. It seems that LibsDisguises and DecentHolograms don't quite work together.

**Comment by alechretien16** [comment]
I couldn't find what other plugin conflicts with, I just removed all of them and uploaded 1x1.
Before that I removed all my settings from purpur.yml, paper.yml etc, and it still happened. I use the latest dev version of ProtocolLib #597.

**Comment by Andre601** [comment]
The only thing I can say is, that DH is simply using the `ItemStack#addUnsafeEnchantment(Enchantment, int)` to apply `Enchantment.DURABILITY` with level 1 to whatever item is used as shown here:

https://github.com/DecentSoftware-eu/DecentHolograms/blob/1684e49e220eb5b6c03ab0bbd1ef92bfb645d7d0/src/main/java/eu/decentsoftware/holograms/api/utils/items/ItemBuilder.java#L207

This is pretty much normal Bukkit API stuff so every server that forks of Spigot or PaperMC should support this unless they patch specific things like not allowing unlogical enchantments (Like Purpur does in the previously linked settings).

Other than that can I not provide more info here. I still doubt it's DH here at fault, but I can be wrong here.

**Comment by alechretien16** [comment]
Hopefully there will be a solution soon, when I was in purpur 1.18.2 it didn't happen, a few days ago I updated to 1.19.2 and it started to happen.
Great plugin DecentHolograms, it's not the same to play without it!

**Comment by Cyberducks99** [comment]
Hello, I confirm the bug with paper 1.19.2-125, decenthologram (Anyversion 1.19) and the last version of protocol lib

**Comment by Andre601** [comment]
> Hello, I confirm the bug with paper 1.19.2-125, decenthologram (Anyversion 1.19) and the last version of protocol lib, No weapon can do damage correctly, especially while being enchanted

The issue was solved on ProtocolLib's end in one of their latest builds, so make sure you're really using the latest build.

**Comment by Cyberducks99** [comment]
The protocollibs update worked, thank you very much

**Comment by d0by1** [comment]
Fixed in v2.5.4 or by updating ProtocolLib.
