### ISSUE TITLE
Can not work with the last ProtocolLib-#597

### ISSUE THREAD

**Issue by shuiqing2046** [DecentSoftware-eu/DecentHolograms#65]
### Just making sure

- [x] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms...
2. add ProtocolLib 5.0.0-SNAPSHOT-b597
3. Right click hologram
4. Server thread terminated
5. server shutdown...

### Solution

①.Downgrade ProtocolLib 5.0.0-SNAPSHOT-b597 to ProtocolLib 5.0.0-SNAPSHOT-b586
②.DecentHolograms-2.5.3 works normally

### Server Version

1.19.2

### Client Version

1.19.1

### Plugin Version

DecentHolograms-2.5.3

### Log

https://paste.helpch.at/wisepewati.md

**Comment by TangJin9487** [comment]
It looks like the problem in `ProtocolLib`.
And `ProtocolLib` has some problems in the newer version for now.

**Comment by Andre601** [comment]
#64

Check PRs next time before opening an issue.
Also, there exist a newer ProtocolLib biild that should fix this.
