### ISSUE TITLE
Adding support for custom mobs (MythicMobs & ModelEngine)

### ISSUE THREAD

**Issue by DarkyCat** [DecentSoftware-eu/DecentHolograms#69]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

I am unable to achieve '...'
I think it would be useful for '...'

### Feature

Hello, I suggest you add support for MythicMobs and ModelEngine. This will add uniqueness to your plugin.

### Alternatives

It would also be possible by doing '...'

**Comment by Andre601** [comment]
There are issues with that.

Namely ME from my knowledge isn't just adding a new entity to the game, but uses remodeled and retextured items put on armor stands to give the illusion of a custom mob.
Meanwhile MythicMobs does afaik just use normal mobs and applies abilities to them.

**Comment by d0by1** [comment]
Hello,

after thinking about it, we decided against working on this feature. Considering the difficulty implementing this and the current situation, it's just not worth adding anything like this. We may re-think this later but for now, I will close this issue.

Thank you for you ideas!
