### ISSUE TITLE
Holograms do not update properly when logging in

### ISSUE THREAD

**Issue by JHarris12345** [DecentSoftware-eu/DecentHolograms#7]
If you have a hologram that has an update interval of like 10 seconds, when you log in to a location, it will not force update the holograms in your location so they will just be null holos (wont return anything)

**Comment by JHarris12345** [comment]
This issue is also for teleporting to holos too

**Comment by tatteaid** [comment]
That doesn't make much sense. Whenever you log in, the holograms are shown to the player (unless it's not visible for them or they're not enabled). And even if that were the case, the null value would go away when the hologram was to update if it were an issue with the holograms. Are you sure the placeholder isn't just null? I tried testing it with a 10-second update interval, but the placeholders would all load for me.
