### ISSUE TITLE
Entity

### ISSUE THREAD

**Issue by Ciferblood** [DecentSoftware-eu/DecentHolograms#71]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

The plugin is cool, there are no problems.

### Feature

Please add that the entity reacts to the movements, that is, does not stop looking at the player.

**Comment by Andre601** [comment]
This is planned for v3.

Suggestions should be made in the Discord server instead of github issues.

**Comment by Ciferblood** [comment]
Okay, i understood, thanks.
