### ISSUE TITLE
Mobs can be interacted

### ISSUE THREAD

**Issue by Ilovemyhous** [DecentSoftware-eu/DecentHolograms#73]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms...
2. Make/Set/Add an intractable mob (cow) in one of your lines.
3. Interact with the cow (empty bucket)

Notes:
- Cutting the wool on sheeps doesn't work.
- I only tried on sheeps and cows.

https://user-images.githubusercontent.com/50217071/188205484-07fa7ae6-87ab-4ebb-b725-7ac4c96c7f53.mp4

### Solution

I think since the sheep's wool can't be cut, there's probably a missing flag for the cow.

### Server Version

git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)

### Client Version

Vanilla 1.18.2 (Optifine)

### Plugin Version

2.6.0

### Log

/

**Comment by d0by1** [comment]
Hello, the milk bucket seems to be a temporary (glitched) item created by the client. We can't really do anything about this as it's the client that thinks the interaction was successful. The item doesn't really exist so I wouldn't really consider this a huge problem.

**Comment by Ilovemyhous** [comment]
Hello, I can confirm, when trying to drink the milk, it doesn't remove effects, nor does it go away from the the inventory, and when doing log-off, and log-in, the milk bucket is replace by a empty bucket.
