### ISSUE TITLE
Random text when using `[` in line

### ISSUE THREAD

**Issue by Josh-65** [DecentSoftware-eu/DecentHolograms#75]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Create a hologram
2. Add [text] as a line
3. see random stuff added replacing `[`
![image](https://user-images.githubusercontent.com/26977075/188320526-eed968b4-75af-433b-ad62-142a841cd535.png)

### Server Version

1.18.2 Paper 387

### Client Version

1.18.2

### Plugin Version

2.7.1

### Log

*

**Comment by d0by1** [comment]
Fixed in v2.7.2.
