### ISSUE TITLE
Incomprehensible error.

### ISSUE THREAD

**Issue by SwartZCoding** [DecentSoftware-eu/DecentHolograms#76]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

Sorry but i have no idea ... It's fully random ...

### Server Version

Current: git-Purpur-1749 (MC: 1.19.1)

### Client Version

1.19.2 Lunar Client

### Plugin Version

2.6.0

### Log

https://pastebin.com/FxFmFPnS

**Comment by Andre601** [comment]
Latest version is 2.7.2.
Please update
