### ISSUE TITLE
Conversion from HolographicDisplays

### ISSUE THREAD

**Issue by TypicalShavonne** [DecentSoftware-eu/DecentHolograms#77]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Make a Hologram in HolographicDisplay with ICON: WHEAT
2. Use ./dh import HolographicDisplays 
3. The hologram imported to DH isnt correctly displayed

### Solution

```
- lines:
  - content: ICON:SNOW_BALL
    height: 0.3
```
the content should be `'#ICON: SNOW_BALL'`

### Server Version

1.17.1

### Client Version

1.18.2

### Plugin Version

DecentHolograms-2.7.2

### Log

https://paste.helpch.at/jupiyarore.md

**Comment by d0by1** [comment]
Hello, this is going to be fixed in the next release, thanks for reporting it!
