### ISSUE TITLE
Convert from CMI

### ISSUE THREAD

**Issue by Candousek** [DecentSoftware-eu/DecentHolograms#78]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms...
2. Convert from CMI
3. Gradient colors are not converted correctly, it's only a static color and there are some characters ({, }) at the start and in the end of the hologram line.

### Server Version

CraftBukkit 1.19.2

### Client Version

1.18.2

### Plugin Version

2.7.2

### Log

Not required

**Comment by Andre601** [comment]
The plugin mentions that support for CMI is limited, so such cases are to be expected. 
In general is it not that easy to detect and convert gradients, as the pattern can (And probably will) be different.

Could you please share the hologram file for CMI and one converted hologram, that has the issues you mentioned?

**Comment by d0by1** [comment]
Seems like not progress has been made here, I will close this for now. You can open a new issue if you wish to continue with this.
