### ISSUE TITLE
About ENTITY

### ISSUE THREAD

**Issue by 3154311518** [DecentSoftware-eu/DecentHolograms#79]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [x] I made sure, that this feature has not been requested yet.

### Problem

Don't want to use npc plugin

### Feature

1. Entities support showing players and can be skinned
2. Entity supports armor stand display (supports custom actions, custom equipment, leather equipment colors, hand-held items, custom avatars)

### Alternatives

none

**Comment by d0by1** [comment]
Hello, thanks for your suggestions!

There are a few problems with this. First of all, I don't think these features would really fit a hologram plugin like this. Also, it's much more difficult than it seems. With the "fake packet" approach we use to display holograms and the current state of the codebase, it's actually near impossible with some major changes. 

Luckily, there is a new, rewritten version being worked on, which is going to solve most of these issues. Anyways, no more entity-related features are currently planned for DH so I would say it's best for you to just use an NPC plugin right now.
