### ISSUE TITLE
Being able to rename Holograms with /dh rename <old name> <new name>

### ISSUE THREAD

**Issue by PalmTamino** [DecentSoftware-eu/DecentHolograms#83]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

I am unable to achieve '...'
I think it would be useful for 'not having to mess around with files or having to do extra steps'

### Feature

Being able to rename a hologram simply by using /dh rename <old name> <new name>

The hologram should also be renamed in files then

### Alternatives

-

**Comment by d0by1** [comment]
Hello, why would you even need to rename a hologram? You can still just rename the file and reload DH btw. I can make this a thing but I just never thought that anyone would need to rename holograms.

**Comment by PalmTamino** [comment]
> Hello, why would you even need to rename a hologram? You can still just rename the file and reload DH btw. I can make this a thing but I just never thought that anyone would need to rename holograms.

I think it should just be possible. Happy you think of making it a thing ;)

**Comment by d0by1** [comment]
Hello, hologram rename command has been added in 2.7.9. Thanks for your suggestion!
