### ISSUE TITLE
Line Alignment Doesnt Work

### ISSUE THREAD

**Issue by Intrigger** [DecentSoftware-eu/DecentHolograms#84]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

Ok, so I created a hologram, then i tried to align some of the lines (both X, Z, XZ ways) but nothing happened and console said that lines were aligned...

### Server Version

1.16.5

### Client Version

1.16.5

### Plugin Version

2.7.5

### Log

There is no log there

**Comment by Andre601** [comment]
Please give some actual information, including steps you did.

Just saying "X doesn't work" doesn't give us any clue on what your issue is. We need actual steps to reproduce.

In short: Follow the issue form more closely.

**Comment by Intrigger** [comment]
Sure, https://youtu.be/Aqh_CSQCE8M

**Comment by Andre601** [comment]
> Sure, https://youtu.be/Aqh_CSQCE8M

I think you missunderstand the purpose of align here.
The command is to align two lines on the same x/z axis. Alignment means that the armor stands (which are the center of the text) are aligned properly.

Like imagine the hologram being at exactly x=0, z=0. If Line 1 is at x=-1 and line 2 at x=0, running the align command makes line 2 align at x=-1, the same coords as line 1.

What you want to use is [`offsetX`](https://wiki.decentholograms.eu/general/commands/hologram-line#dh-l-offsetx-less-than-hologram-greater-than-less-than-page-greater-than-less-than-line-greater-than) and [`offsetZ`](https://wiki.decentholograms.eu/general/commands/hologram-line#dh-l-offsetz-less-than-hologram-greater-than-less-than-page-greater-than-less-than-line-greater-than)

**Comment by Intrigger** [comment]
Ty, this topic might be close
