### ISSUE TITLE
Version 2.7.5 of DecentHolograms break custom skull in 1.8.8

### ISSUE THREAD

**Issue by Fredh1000** [DecentSoftware-eu/DecentHolograms#85]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms 2.7.5 on 1.8.8 server (I tested this on WindSpigot, Paper, NachoSpigot, GuardSpigot and Titanium).
2. Start server.
3. Create holograms with custom skull.
4. This happens:
![2022-11-02_18 05 26](https://user-images.githubusercontent.com/82319919/199555494-5692cb9a-ab25-4638-9513-fa10e1bcc330.png)
![Screenshot (263)](https://user-images.githubusercontent.com/82319919/199555516-6f4ca3e4-9e96-47c2-85ab-190c7b275dbc.png)

### Server Version

1.8.8

### Client Version

1.8.8

### Plugin Version

2.7.5

### Log

I drop logs and hologram config:
  Log: https://pastebin.com/TCXx4MUP
  Holograms config: https://pastebin.com/zs4MTJ4T

**Comment by LewUwU** [comment]
> ### Just making sure
> * [x]  I made sure, this bug is not already known or reported.
> * [x]  I believe, that this bug is fixable.
> 
> ### Reproduction
> 1. Install DecentHolograms 2.7.5 on 1.8.8 server (I tested this on WindSpigot, Paper, NachoSpigot, GuardSpigot and Titanium).
> 2. Start server.
> 3. Create holograms with custom skull.
> 4. This happens:
>    ![2022-11-02_18 05 26](https://user-images.githubusercontent.com/82319919/199555494-5692cb9a-ab25-4638-9513-fa10e1bcc330.png)
>    ![Screenshot (263)](https://user-images.githubusercontent.com/82319919/199555516-6f4ca3e4-9e96-47c2-85ab-190c7b275dbc.png)
> 
> ### Solution
> _No response_
> 
> ### Server Version
> 1.8.8
> 
> ### Client Version
> 1.8.8
> 
> ### Plugin Version
> 2.7.5
> 
> ### Log
> I drop logs and hologram config: Log: https://pastebin.com/TCXx4MUP Holograms config: https://pastebin.com/zs4MTJ4T

Can confirm this

**Comment by d0by1** [comment]
Hi, I'm aware of this issue and it will be fixed in the next release. Thanks for reporting it!
