### ISSUE TITLE
Critical Damage Indicator

### ISSUE THREAD

**Issue by KhrysAK47** [DecentSoftware-eu/DecentHolograms#87]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

I am unable to achieve defining a custom damage indicator for critical hits

I think it would be useful for separating the damage indicators for RPG servers when players deal a vanilla critical damage, to make it more interactive, there are indicators for damage, healing, would make sense to also have the critical one!

### Feature

I would like to see another option implementing a hologram (different than the damage one) for the critical hit, in other words when the player jumps or performs a vanilla critical hit.

**Comment by d0by1** [comment]
Hello, as of 2.7.9, you can now set a custom appearance for critical damage. Thanks for your suggestion!
