### ISSUE TITLE
Holograms do not appear in plotworld

### ISSUE THREAD

**Issue by schiasileon** [DecentSoftware-eu/DecentHolograms#88]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install PlotSquared and create a world
2. Place a holo in the plot-world
3. Restart the server
4. Holograms don't show

### Solution

I believe this bug might be caused because the world is not yet loaded when DH gets initialized. After executing /dh reload the holos show up again. 

### Server Version

Paper 1.19.2

### Client Version

1.19.2

### Plugin Version

2.7.6

### Log

Not applicable

**Comment by d0by1** [comment]
Hello, this should be fixed in version 2.7.7. Thanks for helping me find it!
