### ISSUE TITLE
DecentHolograms using way to many threads leading to a server crash. 

### ISSUE THREAD

**Issue by LuluxClient** [DecentSoftware-eu/DecentHolograms#89]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms...
2. Have 300+ players
3. have 40+ holograms
4. Do a yourkit and Decent will rape your server out of your threads: 

![image](https://user-images.githubusercontent.com/62576432/203747786-aed74db3-800e-44eb-bc1a-83be1b1fd9e7.png)

-----

After making a plugin in order to view how many threads we were using we noticed that when removing DecentHolograms you won't have this issue anymore.  
![image](https://user-images.githubusercontent.com/62576432/203748596-e76c0825-dceb-43d7-be25-87bba0e11302.png)

### Server Version

Pufferfish 1.19.2

### Client Version

1.19.2

### Plugin Version

2.7.4

### Log

private

**Comment by d0by1** [comment]
Hello, this should be fixed in the latest release (2.7.7). Thanks for reporting it!
