### ISSUE TITLE
1.19.3 incompatibility

### ISSUE THREAD

**Issue by SlimeDog** [DecentSoftware-eu/DecentHolograms#91]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

-Build and install Spigot 1.19.3
- Start server
- Read logs

### Solution

Update to support 1.19.3

### Server Version

Spigot 1.19.3-3616

### Client Version

1.19.3

### Plugin Version

2.7.7

### Log

https://whitedog.straight8.com/drops/dh-latest.log

**Comment by geogdog** [comment]
Exactly the same problem here, but with paper 1.19.3. Stack trace is [here](https://paste.md-5.net/ficuzafuta.apache).

**Comment by d0by1** [comment]
Hello, this has been fixes in 2.7.8. Thanks for reporting!

**Comment by SlimeDog** [comment]
Confirmed works correctly with 2.7.8. Thanks.
