### ISSUE TITLE
Hiding a hologram [Doesn't work properly]

### ISSUE THREAD

**Issue by LagClear** [DecentSoftware-eu/DecentHolograms#92]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Create a hologram
2. Disable the hologram with the command
2.1 (issue its still showing up) By relogging it disappears even with reloading the plugin it doesn't solve the issue.

### Solution

Making it disappear on command execution 

### Server Version

1.19.2 Spigot

### Client Version

1.19.2 [Optifine]

### Plugin Version

2.7.7

### Log

None!

**Comment by LagClear** [comment]
Logs https://paste.helpch.at/ekiviwuqix.makefile

**Comment by d0by1** [comment]
Hi, I found the issue and it will be fixed in the next release. Thanks for helping find this!
