### ISSUE TITLE
Holograms not showing up on my crates not sure if it's my plugin issue or decent's

### ISSUE THREAD

**Issue by DebuffPvP** [DecentSoftware-eu/DecentHolograms#94]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

I do not know but my crates plugin has decentholograms as a soft depenency and getting this error from console and holograms not appearing.

### Server Version

1.8.8

### Client Version

1.8.8

### Plugin Version

2.7.7

### Log

https://pastebin.com/qWigJ3WC

**Comment by d0by1** [comment]
Hello, could you please share a full log? Or is this the only error in your console?

**Comment by DebuffPvP** [comment]
This is the only error that shows up

**Comment by d0by1** [comment]
Hello, it seems like the crate plugin started creating holograms before DH was fully loaded. Could you let me know if it's still happening with DH 2.7.10?
