### ISSUE TITLE
Add a option to make damege only display for LivingEntity.

### ISSUE THREAD

**Issue by WMGameLive** [DecentSoftware-eu/DecentHolograms#95]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Feature

Drop an item into fire or cactus or lava or any other ways to make the item disapper, it will also display damage.
I think it should not display it since item is not a living entity. maybe add an option for this.

**Comment by d0by1** [comment]
Hello, this has been fixed in 2.7.9. Thanks for reporting it!
