### ISSUE TITLE
Item in hologram armorstand issue

### ISSUE THREAD

**Issue by Alijkaz** [DecentSoftware-eu/DecentHolograms#96]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms...
2. Make a hologram with item in it
3. Join the server, move out of the hologram render distance
4. Come back to the hologram
5. You'll see an armorstand appearing under the hologram

### Solution

Hello
We are using DecentHolograms (v2.7.8) on Purpur 1.18.2 (Build 1632)
There is a weird issue occurring when there's an Item in the hologram that when you move out of the render distance and comeback again, you'd see an armorstand spawned under the item.

[There's a video we recorded of the issue](https://cdn.discordapp.com/attachments/1004785822219899011/1054081849334448159/DecentHolograms.mp4)

### Server Version

1.18.2

### Client Version

1.19.2 Optifine

### Plugin Version

2.7.8

### Log

https://paste.helpch.at/examusaxuv.rb

**Comment by d0by1** [comment]
Hello, I fixed some issues in 2.7.10, let me know if this is still happening, thanks!
