### ISSUE TITLE
[Feature Request] Hologram classification function. Hologram files can be placed in the subfolder of the folder "holograms"

### ISSUE THREAD

**Issue by luoxiawuchen** [DecentSoftware-eu/DecentHolograms#97]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

I am unable to achieve '...'
I think it would be useful for '...'

When the server has a large number of holograms, 
it will be very chaotic to put all the yml files in the "holograms" folder, which is not easy to quickly find and edit the holograms. It is hoped that the yml files of the holograms can also be load in the subfolders of the "holograms" folder.

### Feature

I would like to see '...'

Hologram yml files can also be loaded in the subfolder of "Holograms" folder
In fact, I suggest that the animation part also handle this way. You can create sub files under the folder "animations" for classification and load yml normally.

![image](https://user-images.githubusercontent.com/64759847/208806935-88bfed63-a817-4570-b04e-a9a40021e5b8.png)

![image](https://user-images.githubusercontent.com/64759847/208807084-1c31919b-dfdb-465b-b724-9a465a7306f6.png)

### Alternatives

It would also be possible by doing '...'

At present, there seems to be no more appropriate plan, but I'm worried that my meaning is not clear enough, because my English is not very good.

Finally, thank you for your patience in reading and bringing this excellent plugin.

**Comment by d0by1** [comment]
Hello, thank you very much for your suggestion. This feature has been added in v2.7.10. Hope you enjoy it!

**Comment by luoxiawuchen** [comment]
> Hello, thank you very much for your suggestion. This feature has been added in v2.7.10. Hope you enjoy it!

Thank you for your response and adoption！
